name: KRISTA WELLS STUDIO
favicon: null
layout_spectrum: 0.02028504409827292
typography_spectrum: 0.7383403719868511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45541379461064935
  lightness: 0.7037499228026718
  saturation: 0.48305922700092196
  rhythmicContrast: 0.9229158211965114
purpose: []
